apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: electrician-secrets
  namespace: turbo-fleet
  labels:
    app.kubernetes.io/name: electrician
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: electrician-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        db-password: "{{ .db_password }}"
        api-key: "{{ .api_key }}"
  data:
    - secretKey: db_password
      remoteRef:
        key: turbo-fleet/electrician
        property: db_password
        version: AWSCURRENT
    - secretKey: api_key
      remoteRef:
        key: turbo-fleet/electrician
        property: api_key
        version: AWSCURRENT
