apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: turbo-fleet

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/part-of: turbo-fleet

images:
  - name: ghcr.io/turbo-the-tech-dev/root/electrician
    newTag: latest
