apiVersion: v1
kind: ServiceAccount
metadata:
  name: electrician
  namespace: turbo-fleet
  labels:
    app.kubernetes.io/name: electrician
    app.kubernetes.io/managed-by: argocd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/turbo-fleet-electrician-role
automountServiceAccountToken: false
